### ISSUE TITLE
[BE] 자동배포(Github Actions)

### ISSUE THREAD

**Issue by ksundong** [codesquad-member-2020/airbnb-11#6]
- dev, master에 push 되었을 때 동작 - 각자 만들어보고 적용 확인
- [x] dev 
   -  서버내에서 실행하는 deploy.sh로 대체...
- [x] master

**Comment by 102092** [comment]
```yml
name: Deploy Spring boot to AWS EC2

on:
  push:
    branches: dev
  pull_request:
    branches: dev

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1

    - name: Grant execute permission for gradle
      run: chomod +x gradlew
      shell: bash
    
    - name: Build with Gradle
      run: ./gradlew build
      shell: bash

```

- 참고 : https://isntyet.github.io/deploy/github-action%EA%B3%BC-aws-code-deploy%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%98%EC%97%AC-spring-boot-%EB%B0%B0%ED%8F%AC%ED%95%98%EA%B8%B0(1)/
- 우선 프로젝트 기본 파일을 생성한 후에, 자동배포 스크립트를 만들어봐야할듯

**Comment by ksundong** [comment]
https://github.com/ksundong/github-actions
직접 해봤는데, 현재 올리신 부분은 build만 됩니다. 즉 CI부분만 되는거죠.
CD를 하기 위해선 S3와 연동을 해야할 것 같습니다.
대부분의 예제는 ECS를 이용해서 docker이미지를 deploy하는데 이렇게 하는걸 원하지는 않을 것 같아요.

**Comment by 102092** [comment]
### workflow file

```yml
name: Test Deploy to AWS EC2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
        
      - name: Make zip file
        run: zip -qq -r ./test-app.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 cp --region us-east-1 ./test-app.zip s3://airbnb11-bucket/test-app.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name deploy-app --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name airbnb11 --s3-location bucket=airbnb11-bucket,bundleType=zip,key=test-app.zip
```

### deploy.sh
```bash
#!/usr/bin/env bash

REPOSITORY=/opt/testapp
cd $REPOSITORY

APP_NAME=action #modul name
JAR_NAME=$(ls $REPOSITORY/build/libs/ | grep '.jar' | tail -n 1)
JAR_PATH=$REPOSITORY/build/libs/$JAR_NAME

CURRENT_PID=$(pgrep -f $APP_NAME)

if [ -z $CURRENT_PID ]
then
  echo "> 종료할것 없음."
else
  echo "> kill -9 $CURRENT_PID"
  kill -15 $CURRENT_PID
  sleep 5
fi

echo "> $JAR_PATH 배포"
nohup java -jar $JAR_PATH > /dev/null 2> /dev/null < /dev/null &

```

### appspec.yml

```yml
version: 0.0
os: linux

files:
  - source: /
    destination: /opt/testapp
permissions:
  - object: /opt/testapp/
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    - location: deploy.sh
      timeout: 60
      runas: root
```
